name: Relase distribution

on:
  push:
    branches:
    - '**'
  delete:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Setup node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: yarn install --frozen-lockfile --non-interactive

    - name: Compile
      run: yarn ttsc

    - name: Release
      uses: './.'
      with:
        push-branch: release-{branch}
        js-override-main: main.ts

  rebuild:
    runs-on: ubuntu-latest
    needs: [build_and_push]

    steps:
    - name: Setup node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Checkout
      uses: actions/checkout@v2

    - name: Extract
      id: extract
      run: |
        echo "##[set-output name=branch;]${GITHUB_REF#refs/heads/}"

    - name: Checkout pre-built
      uses: actions/checkout@v2
      with:
        ref: ${{ steps.extract.outputs.branch }}
        path: prebuilt

    - name: Release
      uses: './prebuilt'
      with:
        push-branch: release-{branch}
        js-override-main: main.ts 
